services:
  traefik:
    image: traefik:v3.1.2
    command:
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
    networks:
      - tunnels-traefik
      - traefik-containers

networks:
  tunnels-traefik:
    external: true
  traefik-containers:
    external: true
